name: Build pdf

on:
  push:

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix build --print-build-logs
      - uses: actions/upload-artifact@v4
        with:
          name: book.pdf
          path: result/book.pdf
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix build .#cover --print-build-logs
      - uses: actions/upload-artifact@v4
        with:
          name: cover.pdf
          path: result/cover.pdf
