name: Build documents

on:
  push:

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix build --print-build-logs
      - uses: actions/upload-artifact@v4
        with:
          name: book
          path: result/book.pdf
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix build .#cover --print-build-logs
      - uses: actions/upload-artifact@v4
        with:
          name: cover
          path: result/cover.pdf
  invitations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix build .#invitation-nl --print-build-logs --out-link result-nl
      - run: nix build .#invitation-en --print-build-logs --out-link result-en
      - uses: actions/upload-artifact@v4
        with:
          name: invitations
          path: |
            result-nl/invitation-nl.pdf
            result-en/invitation-en.pdf
